apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fastapi-app
type: Opaque
stringData:
  db: postgres
  user: pgadmin
  password: 7a779or3
  project_name: Full Stack FastAPI Project
  first_superuser: admin@example.com
  first_superuser_password: supersecurepassword123

